name: pr-workflow

on:
  pull_request:
    branches:
      - dev
            
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: get the code
            uses: actions/checkout@v3

          - name: compile the code
            run: mvn compile
       
          - name: test the code
            run: mvn test

          - name: package the code
            run: mvn package

          - name: print message
            run: echo "thanks for pull request"